site_name: tpm2-tss

docs_dir: doc

theme: readthedocs

nav:
    - Home: README.md
    - INSTALL: INSTALL.md
    - Esys_ActivateCredential: manmd/Esys_ActivateCredential.3.md
    - Esys_Certify: manmd/Esys_Certify.3.md
    - Esys_CertifyCreation: manmd/Esys_CertifyCreation.3.md
    - Esys_ChangeEPS: manmd/Esys_ChangeEPS.3.md
    - Esys_ChangePPS: manmd/Esys_ChangePPS.3.md
    - Esys_Clear: manmd/Esys_Clear.3.md
    - Esys_ClearControl: manmd/Esys_ClearControl.3.md
    - Esys_ClockRateAdjust: manmd/Esys_ClockRateAdjust.3.md
    - Esys_ClockSet: manmd/Esys_ClockSet.3.md
    - Esys_Commit: manmd/Esys_Commit.3.md
    - ESYS_CONTEXT: manmd/ESYS_CONTEXT.3.md
    - Esys_ContextLoad: manmd/Esys_ContextLoad.3.md
    - Esys_ContextSave: manmd/Esys_ContextSave.3.md
    - Esys_Create: manmd/Esys_Create.3.md
    - Esys_CreatePrimary: manmd/Esys_CreatePrimary.3.md
    - Esys_DictionaryAttackLockReset: manmd/Esys_DictionaryAttackLockReset.3.md
    - Esys_DictionaryAttackParameters: manmd/Esys_DictionaryAttackParameters.3.md
    - Esys_Duplicate: manmd/Esys_Duplicate.3.md
    - Esys_ECC_Parameters: manmd/Esys_ECC_Parameters.3.md
    - Esys_ECDH_KeyGen: manmd/Esys_ECDH_KeyGen.3.md
    - Esys_ECDH_ZGen: manmd/Esys_ECDH_ZGen.3.md
    - Esys_EC_Ephemeral: manmd/Esys_EC_Ephemeral.3.md
    - Esys_EncryptDecrypt: manmd/Esys_EncryptDecrypt.3.md
    - Esys_EventSequenceComplete: manmd/Esys_EventSequenceComplete.3.md
    - Esys_EvictControl: manmd/Esys_EvictControl.3.md
    - Esys_FlushContext: manmd/Esys_FlushContext.3.md
    - Esys_GetCapability: manmd/Esys_GetCapability.3.md
    - Esys_GetCommandAuditDigest: manmd/Esys_GetCommandAuditDigest.3.md
    - Esys_GetRandom: manmd/Esys_GetRandom.3.md
    - Esys_GetSessionAuditDigest: manmd/Esys_GetSessionAuditDigest.3.md
    - Esys_GetTestResult: manmd/Esys_GetTestResult.3.md
    - Esys_GetTime: manmd/Esys_GetTime.3.md
    - Esys_Hash: manmd/Esys_Hash.3.md
    - Esys_HashSequenceStart: manmd/Esys_HashSequenceStart.3.md
    - Esys_HierarchyChangeAuth: manmd/Esys_HierarchyChangeAuth.3.md
    - Esys_HierarchyControl: manmd/Esys_HierarchyControl.3.md
    - Esys_HMAC: manmd/Esys_HMAC.3.md
    - Esys_HMAC_Start: manmd/Esys_HMAC_Start.3.md
    - Esys_Import: manmd/Esys_Import.3.md
    - Esys_IncrementalSelfTest: manmd/Esys_IncrementalSelfTest.3.md
    - Esys_Load: manmd/Esys_Load.3.md
    - Esys_LoadExternal: manmd/Esys_LoadExternal.3.md
    - Esys_MakeCredential: manmd/Esys_MakeCredential.3.md
    - Esys_NV_Certify: manmd/Esys_NV_Certify.3.md
    - Esys_NV_ChangeAuth: manmd/Esys_NV_ChangeAuth.3.md
    - Esys_NV_DefineSpace: manmd/Esys_NV_DefineSpace.3.md
    - Esys_NV_Extend: manmd/Esys_NV_Extend.3.md
    - Esys_NV_GlobalWriteLock: manmd/Esys_NV_GlobalWriteLock.3.md
    - Esys_NV_Increment: manmd/Esys_NV_Increment.3.md
    - Esys_NV_Read: manmd/Esys_NV_Read.3.md
    - Esys_NV_ReadLock: manmd/Esys_NV_ReadLock.3.md
    - Esys_NV_ReadPublic: manmd/Esys_NV_ReadPublic.3.md
    - Esys_NV_SetBits: manmd/Esys_NV_SetBits.3.md
    - Esys_NV_UndefineSpace: manmd/Esys_NV_UndefineSpace.3.md
    - Esys_NV_UndefineSpaceSpecial: manmd/Esys_NV_UndefineSpaceSpecial.3.md
    - Esys_NV_Write: manmd/Esys_NV_Write.3.md
    - Esys_NV_WriteLock: manmd/Esys_NV_WriteLock.3.md
    - Esys_ObjectChangeAuth: manmd/Esys_ObjectChangeAuth.3.md
    - Esys_PCR_Allocate: manmd/Esys_PCR_Allocate.3.md
    - Esys_PCR_Event: manmd/Esys_PCR_Event.3.md
    - Esys_PCR_Extend: manmd/Esys_PCR_Extend.3.md
    - Esys_PCR_Read: manmd/Esys_PCR_Read.3.md
    - Esys_PCR_Reset: manmd/Esys_PCR_Reset.3.md
    - Esys_PCR_SetAuthPolicy: manmd/Esys_PCR_SetAuthPolicy.3.md
    - Esys_PCR_SetAuthValue: manmd/Esys_PCR_SetAuthValue.3.md
    - Esys_PolicyAuthorize: manmd/Esys_PolicyAuthorize.3.md
    - Esys_PolicyAuthValue: manmd/Esys_PolicyAuthValue.3.md
    - Esys_PolicyCommandCode: manmd/Esys_PolicyCommandCode.3.md
    - Esys_PolicyCounterTimer: manmd/Esys_PolicyCounterTimer.3.md
    - Esys_PolicyCpHash: manmd/Esys_PolicyCpHash.3.md
    - Esys_PolicyDuplicationSelect: manmd/Esys_PolicyDuplicationSelect.3.md
    - Esys_PolicyGetDigest: manmd/Esys_PolicyGetDigest.3.md
    - Esys_PolicyLocality: manmd/Esys_PolicyLocality.3.md
    - Esys_PolicyNameHash: manmd/Esys_PolicyNameHash.3.md
    - Esys_PolicyNV: manmd/Esys_PolicyNV.3.md
    - Esys_PolicyNvWritten: manmd/Esys_PolicyNvWritten.3.md
    - Esys_PolicyOR: manmd/Esys_PolicyOR.3.md
    - Esys_PolicyPassword: manmd/Esys_PolicyPassword.3.md
    - Esys_PolicyPCR: manmd/Esys_PolicyPCR.3.md
    - Esys_PolicyPhysicalPresence: manmd/Esys_PolicyPhysicalPresence.3.md
    - Esys_PolicyRestart: manmd/Esys_PolicyRestart.3.md
    - Esys_PolicySecret: manmd/Esys_PolicySecret.3.md
    - Esys_PolicySigned: manmd/Esys_PolicySigned.3.md
    - Esys_PolicyTicket: manmd/Esys_PolicyTicket.3.md
    - Esys_PP_Commands: manmd/Esys_PP_Commands.3.md
    - Esys_Quote: manmd/Esys_Quote.3.md
    - Esys_ReadClock: manmd/Esys_ReadClock.3.md
    - Esys_ReadPublic: manmd/Esys_ReadPublic.3.md
    - Esys_Rewrap: manmd/Esys_Rewrap.3.md
    - Esys_RSA_Decrypt: manmd/Esys_RSA_Decrypt.3.md
    - Esys_RSA_Encrypt: manmd/Esys_RSA_Encrypt.3.md
    - Esys_SelfTest: manmd/Esys_SelfTest.3.md
    - Esys_SequenceComplete: manmd/Esys_SequenceComplete.3.md
    - Esys_SequenceUpdate: manmd/Esys_SequenceUpdate.3.md
    - Esys_SetAlgorithmSet: manmd/Esys_SetAlgorithmSet.3.md
    - Esys_SetCommandCodeAuditStatus: manmd/Esys_SetCommandCodeAuditStatus.3.md
    - Esys_SetPrimaryPolicy: manmd/Esys_SetPrimaryPolicy.3.md
    - Esys_Shutdown: manmd/Esys_Shutdown.3.md
    - Esys_Sign: manmd/Esys_Sign.3.md
    - Esys_StartAuthSession: manmd/Esys_StartAuthSession.3.md
    - Esys_Startup: manmd/Esys_Startup.3.md
    - Esys_StirRandom: manmd/Esys_StirRandom.3.md
    - Esys_TestParms: manmd/Esys_TestParms.3.md
    - ESYS_TR: manmd/ESYS_TR.3.md
    - ESYS_TR_defines: manmd/ESYS_TR_defines.3.md
    - Esys_Unseal: manmd/Esys_Unseal.3.md
    - Esys_Vendor_TCG_Test: manmd/Esys_Vendor_TCG_Test.3.md
    - Esys_VerifySignature: manmd/Esys_VerifySignature.3.md
    - Esys_ZGen_2Phase: manmd/Esys_ZGen_2Phase.3.md
    - Fapi_AuthorizePolicy: manmd/Fapi_AuthorizePolicy.3.md
    - Fapi_ChangeAuth: manmd/Fapi_ChangeAuth.3.md
    - fapi-config: manmd/fapi-config.5.md
    - Fapi_CreateKey: manmd/Fapi_CreateKey.3.md
    - Fapi_CreateNv: manmd/Fapi_CreateNv.3.md
    - Fapi_CreateSeal: manmd/Fapi_CreateSeal.3.md
    - Fapi_Decrypt: manmd/Fapi_Decrypt.3.md
    - Fapi_Delete: manmd/Fapi_Delete.3.md
    - Fapi_Encrypt: manmd/Fapi_Encrypt.3.md
    - Fapi_ExportKey: manmd/Fapi_ExportKey.3.md
    - Fapi_ExportPolicy: manmd/Fapi_ExportPolicy.3.md
    - Fapi_Finalize: manmd/Fapi_Finalize.3.md
    - Fapi_Free: manmd/Fapi_Free.3.md
    - Fapi_GetAppData: manmd/Fapi_GetAppData.3.md
    - Fapi_GetCertificate: manmd/Fapi_GetCertificate.3.md
    - Fapi_GetDescription: manmd/Fapi_GetDescription.3.md
    - Fapi_GetInfo: manmd/Fapi_GetInfo.3.md
    - Fapi_GetPlatformCertificates: manmd/Fapi_GetPlatformCertificates.3.md
    - Fapi_GetPollHandles: manmd/Fapi_GetPollHandles.3.md
    - Fapi_GetRandom: manmd/Fapi_GetRandom.3.md
    - Fapi_GetTcti: manmd/Fapi_GetTcti.3.md
    - Fapi_GetTpmBlobs: manmd/Fapi_GetTpmBlobs.3.md
    - Fapi_Import: manmd/Fapi_Import.3.md
    - Fapi_Initialize: manmd/Fapi_Initialize.3.md
    - Fapi_List: manmd/Fapi_List.3.md
    - Fapi_NvExtend: manmd/Fapi_NvExtend.3.md
    - Fapi_NvIncrement: manmd/Fapi_NvIncrement.3.md
    - Fapi_NvRead: manmd/Fapi_NvRead.3.md
    - Fapi_NvSetBits: manmd/Fapi_NvSetBits.3.md
    - Fapi_NvWrite: manmd/Fapi_NvWrite.3.md
    - Fapi_PcrExtend: manmd/Fapi_PcrExtend.3.md
    - Fapi_PcrRead: manmd/Fapi_PcrRead.3.md
    - fapi-profile: manmd/fapi-profile.5.md
    - Fapi_Provision: manmd/Fapi_Provision.3.md
    - Fapi_Quote: manmd/Fapi_Quote.3.md
    - Fapi_SetAppData: manmd/Fapi_SetAppData.3.md
    - Fapi_SetAuthCB: manmd/Fapi_SetAuthCB.3.md
    - Fapi_SetBranchCB: manmd/Fapi_SetBranchCB.3.md
    - Fapi_SetCertificate: manmd/Fapi_SetCertificate.3.md
    - Fapi_SetDescription: manmd/Fapi_SetDescription.3.md
    - Fapi_SetSignCB: manmd/Fapi_SetSignCB.3.md
    - Fapi_Sign: manmd/Fapi_Sign.3.md
    - FapiTestgroup: manmd/FapiTestgroup.3.md
    - Fapi_Unseal: manmd/Fapi_Unseal.3.md
    - Fapi_VerifyQuote: manmd/Fapi_VerifyQuote.3.md
    - Fapi_VerifySignature: manmd/Fapi_VerifySignature.3.md
    - Fapi_WriteAuthorizeNv: manmd/Fapi_WriteAuthorizeNv.3.md
    - tss2-tctildr: manmd/tss2-tctildr.7.md
    - Tss2_TctiLdr_Finalize: manmd/Tss2_TctiLdr_Finalize.3.md
    - Tss2_TctiLdr_FreeInfo: manmd/Tss2_TctiLdr_FreeInfo.3.md
    - Tss2_TctiLdr_GetInfo: manmd/Tss2_TctiLdr_GetInfo.3.md
    - Tss2_TctiLdr_Initialize: manmd/Tss2_TctiLdr_Initialize.3.md
    - tss2-tcti-cmd: manmd/tss2-tcti-cmd.7.md
    - Tss2_Tcti_Cmd_Init: manmd/Tss2_Tcti_Cmd_Init.3.md
    - tss2-tcti-device: manmd/tss2-tcti-device.7.md
    - Tss2_Tcti_Device_Init: manmd/Tss2_Tcti_Device_Init.3.md
    - tss2-tcti-mssim: manmd/tss2-tcti-mssim.7.md
    - Tss2_Tcti_Mssim_Init: manmd/Tss2_Tcti_Mssim_Init.3.md
    - tss2-tcti-swtpm: manmd/tss2-tcti-swtpm.7.md
